. Numpy-> Numerical python
. Scipy-> Scientific python
Scientific Programming: Deals with solving scientific and numerial problems with the help of computer
Examples:
Matlab,Fortran,Apl,Algol,Python(Numpy and scipy are libraries to do scientific programming in python)
Why Numpy and Scipy?
Basic scientific programming operations:
1. Arrays
2. Matrices
3. Integration
4. Differential equation solver
5. Statistics
But python doesn't have all these operations built-in execpt basic operations while these two libraries offers you that


# Numpy
Fundamental python package for python programming
Contains tools and techniques to solve mathematical problems
It is written in C and Python
Operations by Numpy:
Arrays
Linear Algebra
BroadCasting
Random Number Generation
# Similarities between list and numpy Array
1. Storing Data
2. Mutable
3. can be indexed
4. slicing
# differences between list and numpy Array
list can contains different data types
array support only same data type

In [2]:
import numpy as np
a=np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [3]:
a.shape

(4, 4)

In [4]:
a.ndim

2

In [5]:
a.dtype.name

'int32'

In [6]:
a.size

16

In [7]:
type(a)

numpy.ndarray

In [8]:
b=np.array([6,7,8])
b

array([6, 7, 8])

In [9]:
type(b)

numpy.ndarray

In [10]:
# Array Creation
a=np.array([1,2,3])
a

array([1, 2, 3])

In [13]:
print(type(a))
a.dtype

<class 'numpy.ndarray'>


dtype('int32')

In [19]:
c=np.array([(1,2,3),(4.4,5.5,6.6)])
print(c)
d=np.array([(1.5,2,3),(8,9.9,10)])
print(d)

[[1.  2.  3. ]
 [4.4 5.5 6.6]]
[[ 1.5  2.   3. ]
 [ 8.   9.9 10. ]]


In [33]:
e=np.arange(15).reshape(3,5)
print(e)
e.sum(axis=0)
print(e)
e.min(axis=1)
print(e)
f=e.cumsum(axis=1)
print(f)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  3  6 10]
 [ 5 11 18 26 35]
 [10 21 33 46 60]]


# Universal Functions

In [41]:
g=np.arange(6).reshape(2,3)
print(g)
print("Exponential")
print(np.exp(g))
print("Square Root")
print(np.sqrt(g))
h=np.array([(1,2,3),(6,5,4)])
print(h)
print("Add")
print(np.add(g,h))
# Remaining Functions yet to try

[[0 1 2]
 [3 4 5]]
Exponential
[[  1.           2.71828183   7.3890561 ]
 [ 20.08553692  54.59815003 148.4131591 ]]
Square Root
[[0.         1.         1.41421356]
 [1.73205081 2.         2.23606798]]
[[1 2 3]
 [6 5 4]]
Add
[[1 3 5]
 [9 9 9]]
False


# Indexing + Slicing + Iterating

In [68]:
i=np.arange(5)*3
print(i)
i=np.arange(5)**3
print(i)
print(i[2])
j=np.arange(6).reshape(3,2)
print(j)
print(j[2])
print(j[2][1])
k=np.arange(10)**2
print(k)
print(k[0:6])
print(k[5:11])
print(k[0:6:2])
k[0:6:2]=500
print(k)
print(k[::-1])


[ 0  3  6  9 12]
[ 0  1  8 27 64]
8
[[0 1]
 [2 3]
 [4 5]]
[4 5]
5
[ 0  1  4  9 16 25 36 49 64 81]
[ 0  1  4  9 16 25]
[25 36 49 64 81]
[ 0  4 16]
[500   1 500   9 500  25  36  49  64  81]
[ 81  64  49  36  25 500   9 500   1 500]


In [72]:
def f(x,y):
    return x

l=np.fromfunction(f,(5,5),dtype=int)
l
    

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])